version: '2.4'

services:
#  nginx:
#    image: nginx:1.21.1
#    volumes:
#      - /home/ubuntu/velm/nginx.conf:/etc/nginx/nginx.conf
##      - /home/ubuntu/velm:/data/build
#    ports:
#      - 80:80
#    depends_on:
#      - velm
  
  velm:
    image: hyun0404woo/jejuvelm:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/velm-db?useUnicode=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_PROFILES_ACTIVE: dev
#      JAVA_OPTS: -Dspring.profiles.active=dev
    ports:
      - "38080:8080"
    restart: always
    entrypoint: ["bash", "-c"]
    command:
      - |  
        java -jar app.jar
    depends_on:
      mysql:
        condition: service_healthy
    
  # $ mysql -uroot -h127.0.0.1 -p
  mysql:
    image: mysql:5.7
    platform: "linux/x86_64"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=velm-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    healthcheck:
      test: "/usr/bin/mysql -uuser -p1234 --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10