version: '2.4'

services:
  nginx:
    image: nginx:1.21.1
    volumes:
      - /home/azureuser/jeju/server/nginx.conf:/etc/nginx/nginx.conf
      - /home/azureuser/jeju/front/out:/data/build
      - /home/azureuser/jeju/static:/data/static
#      - /etc/letsencrypt/live/jejuvelue.link/fullchain.pem:/etc/letsencrypt/live/jejuvelue.link/fullchain.pem
#      - /etc/letsencrypt/live/jejuvelue.link/privkey.pem:/etc/letsencrypt/live/jejuvelue.link/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    restart: always
#    depends_on:
#      velue:
#        condition: service_healthy

  velue:
    image: hyun0404woo/jejuvelm:latest
    volumes:
      - /home/azureuser/jeju/static/docs:/static/docs
      - /home/azureuser/jeju/static/predata:/static/predata
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/velm-db?useUnicode=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    restart: always
#    entrypoint: ["bash", "-c"]
#    command:
#      - |  
#        java -Dspring.profiles.active=dev -jar app.jar
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP | exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
    
  # $ mysql -uroot -h127.0.0.1 -p
  mysql:
    image: mysql:5.7
    platform: "linux/x86_64"
    volumes:
      - /home/azureuser/jeju/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=velm-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: "/usr/bin/mysql -uuser -p1234 --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10