spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/Desktop/Dev/prod/goormton/goormton
    url: jdbc:h2:file:./build/data/testdb
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: create-drop
    logging.level:
      org.hibernate.SQL: debug
  sql:
    init:
      mode: always
  profiles:
    group:
      dev: "dev"
      prod: "prod"
      test: "test"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

jwt:
  access-secret: ajhdflashdflhasdkjfhasjdhfasdfasfasdfasdfasdfawef
  refresh-secret: ajhdflashdflhasdkjfhasjdhfasdfasfasdfasdfasdfawef

static:
  place-image-path: ./src/main/resources/static/placeimage/
  place-data-path: ./src/main/resources/static/predata/placedata.csv

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring:
  config:
    activate:
      on-profile: "dev"
    import: mysql-datasource.yml
  jpa:
    hibernate:
      ddl-auto: create
    logging.level:
      org.hibernate.SQL: debug

static:
  place-image-path: ./static/
  place-data-path: ./static/predata/placedata.csv

---
spring:
  config:
    activate:
      on-profile: "prod"
    import: mysql-datasource.yml
  jpa:
    hibernate:
      ddl-auto: none
      
static:
  place-image-path: ./static/